# config.yml The config recipe.
recipe: default.v1
language: en

pipeline: # ------- NLU

  - name: submodules.custom_components.language_handlers.language_handler.LanguageHandlerAndTranslator

    # Load Language model
  - name: SpacyNLP
    model: en_core_web_trf
    case_sensitive: False

    # Tokenizer
  - name: SpacyTokenizer
    intent_tokenization_flag: True # to use multi intents
    intent_split_symbol: "+"

    # Featurizers
  - name: RegexFeaturizer
  - name: SpacyFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer # one hot encoding
  - name: CountVectorsFeaturizer # char level n-grams
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

#  - name: submodules.custom_components.featurizers.gpt_vectorized_featurizer.GPTVectorFeaturizer

    # Entity Extractor
  - name: SpacyEntityExtractor
    dimensions: [ "PERSON" ]

    # Intent and Entity Extractor
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true


#  - name: submodules.custom_components.intent_classifiers.zero_shot_bart_intent_classifier.ZeroShotBartIntentClassifier
#    candidate_class_size: 5
#    threshold: 0.4 # threshold for zero shot classifier (must be lower than or equal to fallback_classifier_threshold)
#    fallback_classifier_threshold: 0.6 # fallback_classifier_threshold
#    fallback_classifier_ambiguity_threshold: 0.1: 0.6 # fallback_classifier_threshold

  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1

policies: # ------- Dialog Management

  - name: MemoizationPolicy
  - name: RulePolicy

  - name: UnexpecTEDIntentPolicy
    max_history: 8
    epochs: 100

  - name: TEDPolicy
    max_history: 16
    epochs: 100
    constrain_similarities: true
