# config.yml The config recipe.
recipe: default.v1
language: en

pipeline: # ------- NLU

  - name: submodules.custom_components.language_handlers.language_handler.LanguageHandlerAndTranslator

    # Load Language model
  - name: SpacyNLP
    model: en_core_web_sm
    case_sensitive: False

    # Tokenizer
  - name: SpacyTokenizer
    intent_tokenization_flag: True        # to use multi intents
    intent_split_symbol: "+"

    # Featurizers
  - name: RegexFeaturizer                 # Sparse featurizer
  - name: SpacyFeaturizer                 # Dense featurizer
  - name: LexicalSyntacticFeaturizer      # Sparse featurizer
  - name: CountVectorsFeaturizer          # Sparse featurizer | one hot encoding
  - name: CountVectorsFeaturizer          # Sparse featurizer | char level n-grams
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

    # Entity Extractor
  - name: SpacyEntityExtractor
    dimensions: [ "PERSON" ]

    # Intent and Entity Extractor
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

  - name: submodules.custom_components.intent_classifiers.zero_shot_bart_intent_classifier.ZeroShotBartIntentClassifier
    threshold: 0.4
    ambiguity_threshold: 0.05
    candidate_class_size: 5
    top_intent_confidence_threshold: 0.95
    fallback_classifier_threshold: 0.6 # must be same as FallbackClassifier
    fallback_classifier_ambiguity_threshold: 0.1 # must be same as FallbackClassifier

  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1

policies: # ------- Dialog Management

  - name: MemoizationPolicy
    max_history: 16

  - name: AugmentedMemoizationPolicy
    max_history: 24

  - name: RulePolicy

  - name: UnexpecTEDIntentPolicy
    max_history: 16
    epochs: 200

  - name: TEDPolicy
    max_history: 16
    epochs: 200
    constrain_similarities: true
