# config.yml The config recipe.
recipe: default.v1
language: en

pipeline: # -------------------------------------------------- NLU -----------------------------------------------------

    # Load Language model
  - name: SpacyNLP
    model: en_core_web_lg
    case_sensitive: False

    # Tokenizer
  - name: SpacyTokenizer
    intent_tokenization_flag: True                      # to use multi intents
    intent_split_symbol: "+"

    # Featurizers
  - name: RegexFeaturizer                               # Sparse featurizer

  - name: SpacyFeaturizer                               # Dense featurizer

  - name: LexicalSyntacticFeaturizer                    # Sparse featurizer
  - name: CountVectorsFeaturizer                        # Sparse featurizer | one hot encoding
  - name: CountVectorsFeaturizer                        # Sparse featurizer | char level n-grams
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

    # Intent and Entity Extractor
  - name: DIETClassifier
    epochs: 150
    constrain_similarities: true

  - name: submodules.custom_components.intent_classifiers.zero_shot_bart_intent_classifier.ZeroShotBartIntentClassifier
    threshold: 0.5
    ambiguity_threshold: 0.05
    candidate_class_size: 7
    top_intent_confidence_threshold: 0.95
    fallback_classifier_threshold: 0.4                    # must be same as FallbackClassifier threshold
    fallback_classifier_ambiguity_threshold: 0.1          # must be same as FallbackClassifier ambiguity_threshold

  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1

policies: # -------------------------------------------- Dialog Management --------------------------------------------

  - name: MemoizationPolicy
    max_history: 32

  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: action_default_fallback
    enable_fallback_prediction: true

  - name: UnexpecTEDIntentPolicy
    max_history: 32
    epochs: 100

  - name: TEDPolicy
    max_history: 32
    epochs: 100
    constrain_similarities: true
