recipe: default.v1
language: en

pipeline:

  # Tokenizer
  - name: SpacyTokenizer
    intent_tokenization_flag: True                      # to use multi intents
    intent_split_symbol: "+"

  # Featurizers
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: LanguageModelFeaturizer
    model_name: "gpt"
    model_weights: "openai-gpt"

  - name: CountVectorsFeaturizer                        # Sparse featurizer | one hot encoding
  - name: CountVectorsFeaturizer                        # Sparse featurizer | char level n-grams
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  # Intent and Entity Extractor
  - name: DIETClassifier
    epochs: 150
    constrain_similarities: true

  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1

policies: # -------------------------------------------- Dialog Management --------------------------------------------

  - name: MemoizationPolicy
    max_history: 32

  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: action_default_fallback
    enable_fallback_prediction: true

  - name: UnexpecTEDIntentPolicy
    max_history: 32
    epochs: 100

  - name: TEDPolicy
    max_history: 32
    epochs: 100
    constrain_similarities: true